# Working in the lab

In the SCANN lab, we practice careful, deliberate, open science. This means that every person in the lab has a responsibility to make sure their projects are well-documented, reproducible, and undertaken with an eye toward the future. The following are a few more specific guidelines.

## Rights
* **You have the right to a work environment free from prejudice, bias, harassment, and discrimination**
We have a strong focus on inclusion, diversity, and a harassment-free workplace. At all times, we treat each other, our participants, and our science with respect. (This does not mean we cannot argue - passionately, if need be. Dissenting opinions and knowing when to stand up for your opinion and when to back down, are in fact critical aspects of the scientific process.) You have the right to a workplace culture that supports you, your career, and your expressions (as long as these rights don’t violate the rights of others.)

* **You have the right to make mistakes.** No one is perfect. Dr. Weisberg has (probably) made bigger mistakes than you will during your time in the lab. (Ask him sometime.) Science is hard, and the work we do is at the edge of knowledge. This is very cool, but it also means we are much more likely to make mistakes that we don’t catch right away. Below, you’ll see what your responsibilities are if (when) you make a mistake.

* **You have the right to have ideas.** No matter how strange.

* **You have the right to criticize ideas.** You are expected to criticize your own ideas! But you should also think critically about the ideas of others (including and perhaps especially Dr. Weisberg), and when you criticize an idea: focus your criticism on the idea, not on the person who came up with the idea, including yourself!

* **You have the right to maintain a healthy work-life balance.** I hope that you love working in the lab, but this does not mean slavish devotion ;).

## Responsibilities
* **All lab members will prioritize a healthy and supportive lab culture.**
  The SCANN lab is deeply committed to maintaining a harassment-free and inclusive culture. All lab members are expected to treat each other with respect, professionalism, and general courtesy. This also means you have a responsibility to ensuring you maintain a healthy work-life balance (whatever this means for you). We strive for diversity, anti-racism, and inclusivity. Some guiding principles are [here](https://coco-net.org/wp-content/uploads/2019/11/Coco-WhiteSupCulture-ENG4.pdf). We also follow [UF harassment policy](https://hr.ufl.edu/forms-policies/policies-managers/sexual-harassment/).

* **This is a professional work environment.**
We keep things professional for ourselves, when we interact with people outside of the lab, and *most especially* for **participants**. We owe our participants a huge debt of gratitude, regardless of their compensation, because they are taking the time to provide us with their data. Treat each one with the utmost respect and care. Professionalism means appropriate dress and respectful demeanor (cursing, loud music, messiness discouraged). Professionalism also means upholding your commitments - being on time for your shifts; cleaning up after yourself; sticking to deadlines. It also means communicating effectively. (To reiterate - you can make mistakes! Professionalism means communicating about them when you do!) Lastly, professionalism means appropriateness in all things (including humor; off-color jokes or jokes at the expense of others will not be tolerated). This applies for all times you're at work, but again *especially* when running participants. Finally - professionalism does NOT MEAN no fun! Work should absolutely be fun in a way that is fun for everyone!

* **You are a team member first.**
  As a lab, we can only thrive by relying and counting on each other. Treat everyone in the lab (and anyone related to the lab, including participants, collaborators, mentors) with respect and care. Respect their time, their preferred hours, and their needs. Help them when they ask (within reason), and help build a culture of respect and honesty.
Work with care. Measure twice, cut once. Document your workflows. Save and backup all raw data and code (on a minimum of two of these locations: Hipergator, Dropbox, OneDrive). In preparation phase, make sure everything is clearly labeled, and the experimental paradigm captures data as expected. It is best practice to write analysis code on simulated or pilot data as proof of principle and good sanity checking. In the experiment phase, make sure raw data are being regularly backed up. In the analysis phase, make sure difficult-to-reproduce products are also backed up, and that all analyses are reproducible and documented. In the submission phase, all materials should be uploaded to OSF, OpenNeuro, or another online repository in preparation for submission.

* **Our goal is research products**
  Posters, presentations, and publications are the traditional academic products, and you will be expected to produce or contribute to these as a member of the lab. But we also value contributions of: data sets (documented and described), software packages (and analysis pipelines), and ‘reproducible sandboxes’ (Jupyter Notebooks). These research products are rarely peer-reviewed, but provide invaluable tools for the broader research world and their creation is not taken lightly.
