
# Communication

Science, especially as practiced in the SCANN Lab, is a collaborative endeavor, which means good communication is key. Here are the main ways the lab communicates.

One thing we often forget about is communicating with ourselves. This means *good documentation* so people don't have to reinvent the wheel. We will have the following:

## Lab meeting
Lab meetings are held weekly during the semester, Tuesday 12pm-2pm for the fall 2020 semester, and intermittently through the summer. Lab meetings are approximately two hours long. The first ~20-30 minutes consist of lab updates in which each lab member briefly (5 minutes or so) explains what constituted the bulk of their work that week; what progress was made, what hurdles were hit; and any general info they encountered relevant to the lab. The remaining 1-1.5 hours is provided for one lab member to give a presentation. The presentation can range widely (almost all formats are acceptable). Here are a few examples:

* A journal club / discussion of an article

* A project proposal / plan

* A discussion about a general issue in science (e.g., preregistration, p-hacking, etc.)

* Technique or tutorial (relevant to almost anything in the lab - e.g., Git or how head direction cells work; an MVPA crash course or how to organize folders for a project)

* A data talk (e.g., where you have data but need help thinking through what it means, what to do next, or what you might not have thought of)

* A polished (practice) presentation or job talk

## In-person meetings

In-person meetings (in person or via Zoom) are a great way to work directly and solve a particular problem or make a plan of action. But they are also usually very time-intensive. Lab members may have regularly scheduled meetings with me during the semester, but anyone should always feel free to schedule a meeting. Before asking about a meeting, however, ask yourself three things:

1. Could this be solved via email?
  If yes, send email. If no...

2. What is the purpose of the meeting? (In other words, what is the agenda?) Make sure the purpose is in the email to schedule it.

3. What are the necessary inputs to the meeting? (Do we have all information we need to facilitate the meeting; if not, what are we waiting for? Are all necessary people involved?)

4. What are the expected outputs? Always ask yourself at the end of the meeting whether you know what the action items are (who will do what).

## Slack

Our lab [Slack](scannlab.slack.com) is the source for daily lab communication. Our communication via Slack takes three forms.

* Easy instant messaging (@everyone; @steve weisberg)

* Communication about a particular topic. This is the purpose for channels. (#neurofeedback, #lab-purchasing). Feel free to start your own channel about a specific topic. Don't forget to invite the relevant people!

* Updates and integration with other services. Check out integrations with Google Calendar, Github, Trello, and more!

## Trello

Our lab to-do lists. The [Onboarding checklist] is on Trello. I recommend that everyone use Trello as their own to-do list manager, but I would strongly encourage using the shared to-do list feature for projects we're working on. Note that cards can be assigned due dates and assigned to specific people, who can indicate when they have finished particular tasks.

## Email

Official communication, notifications, etc. I sometimes use interchangeably via Slack. The one difference is any communication regarding participants absolutely needs to happen through UF email.
